services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3003"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env